"""Initial migration

Revision ID: 1e33ec03e6f0
Revises: 
Create Date: 2026-02-16 22:51:04.995581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e33ec03e6f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_xid', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_gid', sa.String(length=200), nullable=True),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otm_object_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_name')
    )
    op.create_table('metadata_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['otm_object_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_gid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('item_xid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('domain_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('otm_sync_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index('ix_item_sync_status', ['otm_sync_status'], unique=False)
        batch_op.create_unique_constraint('uq_domain_xid', ['domain_name', 'item_xid'])
        batch_op.create_unique_constraint('uq_item_gid', ['item_gid'])
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_item_gid', type_='unique')
        batch_op.drop_constraint('uq_domain_xid', type_='unique')
        batch_op.drop_index('ix_item_sync_status')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('otm_sync_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('domain_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('item_xid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('item_gid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('metadata_fields')
    op.drop_table('otm_object_metadata')
    op.drop_table('invoice_json')
    # ### end Alembic commands ###
