"""add invoice_json table

Revision ID: 086be5775d9d
Revises: 21191cdf4c78
Create Date: 2026-01-27 20:13:27.324034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086be5775d9d'
down_revision = '21191cdf4c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_xid', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_gid', sa.String(length=200), nullable=True),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_json')
    # ### end Alembic commands ###
