"""empty message

Revision ID: 1192f4cb766a
Revises: a0f21b06eec0
Create Date: 2026-04-08 14:52:37.249498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1192f4cb766a'
down_revision = 'a0f21b06eec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_base_field_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_base_field_config', schema=None) as batch_op:
        batch_op.drop_column('data_type')

    # ### end Alembic commands ###
