"""add role to users

Revision ID: 168080dc7e54
Revises: 97976019f74f
Create Date: 2026-01-14 20:45:44.186149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168080dc7e54'
down_revision = '97976019f74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
