"""modified variable length

Revision ID: 21191cdf4c78
Revises: c6905b960901
Create Date: 2026-01-21 10:37:17.403893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21191cdf4c78'
down_revision = 'c6905b960901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
