"""add json columns

Revision ID: 2b56f3e6072f
Revises: 168080dc7e54
Create Date: 2026-01-20 16:35:26.308498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b56f3e6072f'
down_revision = '168080dc7e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('response_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('invoice_xid',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('invoice_num',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('invoice_num',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('invoice_xid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('source_type')
        batch_op.drop_column('response_json')
        batch_op.drop_column('request_json')

    # ### end Alembic commands ###
