"""Register Order Release models

Revision ID: 2e28fc737eb5
Revises: c0d9326b5430
Create Date: 2026-05-15 15:00:20.958189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e28fc737eb5'
down_revision = 'c0d9326b5430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otm_field_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('otm_db_path', sa.String(), nullable=True),
    sa.Column('field_group', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otm_db_path')
    )
    with op.batch_alter_table('otm_field_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otm_field_registry_id'), ['id'], unique=False)

    op.create_table('user_field_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('selected_fields', sa.JSON(), nullable=False),
    sa.Column('preferred_domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_field_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_field_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_field_preferences_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_field_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_field_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_field_preferences_id'))

    op.drop_table('user_field_preferences')
    with op.batch_alter_table('otm_field_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otm_field_registry_id'))

    op.drop_table('otm_field_registry')
    # ### end Alembic commands ###
