"""Add OTM metadata models

Revision ID: 59ff338bf471
Revises: 086be5775d9d
Create Date: 2026-02-10 20:54:42.912690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ff338bf471'
down_revision = '086be5775d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otm_object_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_name')
    )
    op.create_table('metadata_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['otm_object_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_fields')
    op.drop_table('otm_object_metadata')
    # ### end Alembic commands ###
