"""add users

Revision ID: 97976019f74f
Revises: abdef0d4adae
Create Date: 2026-01-14 19:34:47.742027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97976019f74f'
down_revision = 'abdef0d4adae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_xid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('invoice_num',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_num',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('invoice_xid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
