"""create invoice table

Revision ID: abdef0d4adae
Revises: 
Create Date: 2026-01-09 14:23:48.079968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abdef0d4adae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_xid', sa.String(length=50), nullable=False),
    sa.Column('invoice_num', sa.String(length=50), nullable=False),
    sa.Column('transmission_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_xml', sa.Text(), nullable=True),
    sa.Column('response_xml', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_xid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoice_num', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transmission_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('request_xml', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_xml', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_pkey'))
    )
    op.drop_table('invoices')
    # ### end Alembic commands ###
