"""Added OrderBase data model

Revision ID: c0d9326b5430
Revises: 1192f4cb766a
Create Date: 2026-04-14 12:12:03.680861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d9326b5430'
down_revision = '1192f4cb766a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_base_gid', sa.String(length=255), nullable=False),
    sa.Column('order_base_xid', sa.String(length=255), nullable=False),
    sa.Column('order_base_name', sa.String(length=255), nullable=True),
    sa.Column('domain_name', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('otm_sync_status', sa.String(length=50), nullable=True),
    sa.Column('sync_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_base_gid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_base')
    # ### end Alembic commands ###
