"""add variable length

Revision ID: c6905b960901
Revises: 2b56f3e6072f
Create Date: 2026-01-21 10:03:34.220166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6905b960901'
down_revision = '2b56f3e6072f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_field_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('display_text', sa.String(length=200), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('data_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('invoice_field_config')
    # ### end Alembic commands ###
